apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-lcm
  labels:
    app: lcm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-lcm
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-lcm
subjects:
- kind: ServiceAccount
  name: k8s-lcm
  namespace: lcm
roleRef:
  kind: ClusterRole
  name: k8s-lcm
  apiGroup: rbac.authorization.k8s.io
